include: package:lint/analysis_options.yaml
linter:
  rules:
    prefer_constructors_over_static_methods : false
    constant_identifier_names: false
    sort_pub_dependencies: false
    directives_ordering: false
    